#!/usr/bin/env bash
# =============================================================
#  MCMarPanel -- Interactive Setup & Deploy Script
#  Usage: bash setup.sh   (desde dentro de la carpeta docker/)
# =============================================================

set -e

BOLD="\033[1m"
CYAN="\033[1;36m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RED="\033[1;31m"
RESET="\033[0m"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

load_env() {
    local src="$ENV_FILE"
    [[ ! -f "$src" ]] && src="$ENV_EXAMPLE"
    if [[ -f "$src" ]]; then
        while IFS='=' read -r key value; do
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            value="${value%%#*}"
            value="${value//\"/}"
            value="${value// /}"
            printf -v "$key" '%s' "$value"
        done < "$src"
    fi
}

prompt() {
    local var_name="$1"
    local label="$2"
    local current="${!var_name}"
    local input
    echo -n "  ${label} [${YELLOW}${current}${RESET}]: "
    read -r input
    [[ -n "$input" ]] && printf -v "$var_name" '%s' "$input"
}

write_env() {
    cat > "$ENV_FILE" <<EOF
# MCMarPanel Configuration -- generated by setup.sh
# $(date)

PORT=$PORT

RCON_HOST=$RCON_HOST
RCON_PORT=$RCON_PORT
RCON_PASSWORD=$RCON_PASSWORD

MC_LOCAL_HOST=$MC_LOCAL_HOST
MC_LOCAL_PORT=$MC_LOCAL_PORT

MC_EXT_HOST=$MC_EXT_HOST
MC_EXT_PORT=$MC_EXT_PORT
EOF
}

check_docker() {
    if ! command -v docker &>/dev/null; then
        echo -e "${RED}[ERROR] Docker no esta instalado.${RESET}"
        echo "  Instalalo con: curl -fsSL https://get.docker.com | sh"
        exit 1
    fi
    if ! docker compose version &>/dev/null; then
        echo -e "${RED}[ERROR] Docker Compose plugin no encontrado.${RESET}"
        exit 1
    fi
}

clear
echo ""
echo -e "${CYAN}+------------------------------------------+"
echo -e "|    MCMarPanel -- Docker Setup Wizard        |"
echo -e "+------------------------------------------+${RESET}"
echo ""

load_env

while true; do
    echo -e "${BOLD}Configuracion actual:${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Panel"
    echo -e "  |    PORT          = ${YELLOW}${PORT:-3007}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  RCON (control del servidor MC)"
    echo -e "  |    RCON_HOST     = ${YELLOW}${RCON_HOST:-x}${RESET}"
    echo -e "  |    RCON_PORT     = ${YELLOW}${RCON_PORT:-x}${RESET}"
    echo -e "  |    RCON_PASSWORD = ${YELLOW}${RCON_PASSWORD:-(vacia)}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Servidor Minecraft (red local)"
    echo -e "  |    MC_LOCAL_HOST = ${YELLOW}${MC_LOCAL_HOST:-x}${RESET}"
    echo -e "  |    MC_LOCAL_PORT = ${YELLOW}${MC_LOCAL_PORT:-x}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Servidor Minecraft (externo)"
    echo -e "  |    MC_EXT_HOST   = ${YELLOW}${MC_EXT_HOST:-x}${RESET}"
    echo -e "  |    MC_EXT_PORT   = ${YELLOW}${MC_EXT_PORT:-x}${RESET}"
    echo "  +------------------------------------------------"
    echo ""
    echo -e "  ${BOLD}Que quieres hacer?${RESET}"
    echo "   1) Editar configuracion"
    echo "   2) Guardar y desplegar  (docker compose up -d --build)"
    echo "   3) Solo guardar .env    (sin desplegar)"
    echo "   4) Ver logs del contenedor"
    echo "   5) Detener contenedor"
    echo "   6) Salir"
    echo ""
    echo -n "  Opcion: "
    read -r opt

    case "$opt" in
    1)
        echo ""
        echo -e "${BOLD}-- Panel -----------------------------------------------${RESET}"
        prompt PORT         "Puerto del panel (PORT)"
        echo -e "${BOLD}-- RCON ------------------------------------------------${RESET}"
        prompt RCON_HOST     "IP del servidor MC (RCON_HOST)"
        prompt RCON_PORT     "Puerto RCON (RCON_PORT)"
        prompt RCON_PASSWORD "Contrasena RCON (RCON_PASSWORD)"
        echo -e "${BOLD}-- Conexion local --------------------------------------${RESET}"
        prompt MC_LOCAL_HOST "IP local MC (MC_LOCAL_HOST)"
        prompt MC_LOCAL_PORT "Puerto local MC (MC_LOCAL_PORT)"
        echo -e "${BOLD}-- Conexion externa ------------------------------------${RESET}"
        prompt MC_EXT_HOST   "Host externo MC (MC_EXT_HOST)"
        prompt MC_EXT_PORT   "Puerto externo MC (MC_EXT_PORT)"
        echo ""
        ;;
    2)
        check_docker
        write_env
        echo -e "${GREEN}[OK] .env guardado${RESET}"
        echo -e "${CYAN}[>>] Construyendo imagen y levantando contenedor...${RESET}"
        cd "$SCRIPT_DIR"
        docker compose up -d --build
        echo ""
        LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || LOCAL_IP="localhost"
        echo -e "${GREEN}[OK] MCMarPanel desplegado.${RESET}"
        echo -e "     Accede en: ${CYAN}http://${LOCAL_IP}:${PORT:-3007}${RESET}"
        echo ""
        break
        ;;
    3)
        write_env
        echo -e "${GREEN}[OK] .env guardado (sin desplegar).${RESET}"
        echo ""
        ;;
    4)
        cd "$SCRIPT_DIR"
        echo -e "${CYAN}-- Logs (Ctrl+C para salir) -------------------------${RESET}"
        docker compose logs -f
        ;;
    5)
        cd "$SCRIPT_DIR"
        echo -e "${YELLOW}[>>] Deteniendo contenedor...${RESET}"
        docker compose down
        echo -e "${GREEN}[OK] Contenedor detenido.${RESET}"
        echo ""
        ;;
    6)
        echo "Saliendo."
        exit 0
        ;;
    *)
        echo -e "${RED}Opcion invalida.${RESET}"
        echo ""
        ;;
    esac
done