#!/usr/bin/env bash
# =============================================================
#  MCMarPanel -- Interactive Setup & Deploy Script
#  Usage: bash SETUP.sh   (from inside the docker/ folder)
# =============================================================

set -e

BOLD="\033[1m"
CYAN="\033[1;36m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RED="\033[1;31m"
RESET="\033[0m"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

load_env() {
    local src="$ENV_FILE"
    [[ ! -f "$src" ]] && src="$ENV_EXAMPLE"
    if [[ -f "$src" ]]; then
        while IFS='=' read -r key value; do
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            value="${value%%#*}"
            value="${value//\"/}"
            value="${value// /}"
            printf -v "$key" '%s' "$value"
        done < "$src"
    fi
}

prompt() {
    local var_name="$1"
    local label="$2"
    local current="${!var_name}"
    local input
    echo -n "  ${label} [${YELLOW}${current}${RESET}]: "
    read -r input
    [[ -n "$input" ]] && printf -v "$var_name" '%s' "$input"
}

write_env() {
    cat > "$ENV_FILE" <<EOF
# MCMarPanel Configuration -- generated by SETUP.sh
# $(date)

PORT=$PORT

RCON_HOST=$RCON_HOST
RCON_PORT=$RCON_PORT
RCON_PASSWORD=$RCON_PASSWORD

MC_LOCAL_HOST=$MC_LOCAL_HOST
MC_LOCAL_PORT=$MC_LOCAL_PORT

MC_EXT_HOST=$MC_EXT_HOST
MC_EXT_PORT=$MC_EXT_PORT
EOF
}

check_docker() {
    if ! command -v docker &>/dev/null; then
        echo -e "${RED}[ERROR] Docker is not installed.${RESET}"
        echo "  Install it with: curl -fsSL https://get.docker.com | sh"
        exit 1
    fi
    if ! docker compose version &>/dev/null; then
        echo -e "${RED}[ERROR] Docker Compose plugin not found.${RESET}"
        exit 1
    fi
}

clear
echo ""
echo -e "${CYAN}+------------------------------------------+"
echo -e "|    MCMarPanel -- Docker Setup Wizard        |"
echo -e "+------------------------------------------+${RESET}"
echo ""

load_env

while true; do
    echo -e "${BOLD}Current configuration:${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Panel"
    echo -e "  |    PORT          = ${YELLOW}${PORT:-3007}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  RCON (Minecraft server control)"
    echo -e "  |    RCON_HOST     = ${YELLOW}${RCON_HOST:-x}${RESET}"
    echo -e "  |    RCON_PORT     = ${YELLOW}${RCON_PORT:-x}${RESET}"
    echo -e "  |    RCON_PASSWORD = ${YELLOW}${RCON_PASSWORD:-(empty)}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Minecraft Server (local network)"
    echo -e "  |    MC_LOCAL_HOST = ${YELLOW}${MC_LOCAL_HOST:-x}${RESET}"
    echo -e "  |    MC_LOCAL_PORT = ${YELLOW}${MC_LOCAL_PORT:-x}${RESET}"
    echo "  +------------------------------------------------"
    echo "  |  Minecraft Server (external)"
    echo -e "  |    MC_EXT_HOST   = ${YELLOW}${MC_EXT_HOST:-x}${RESET}"
    echo -e "  |    MC_EXT_PORT   = ${YELLOW}${MC_EXT_PORT:-x}${RESET}"
    echo "  +------------------------------------------------"
    echo ""
    echo -e "  ${BOLD}What do you want to do?${RESET}"
    echo "   1) Edit configuration"
    echo "   2) Save and deploy  (docker compose up -d --build)"
    echo "   3) Save .env only   (without deploying)"
    echo "   4) View container logs"
    echo "   5) Stop container"
    echo "   6) Exit"
    echo ""
    echo -n "  Option: "
    read -r opt

    case "$opt" in
    1)
        echo ""
        echo -e "${BOLD}-- Panel -----------------------------------------------${RESET}"
        prompt PORT         "Panel port (PORT)"
        echo -e "${BOLD}-- RCON ------------------------------------------------${RESET}"
        prompt RCON_HOST     "MC server IP (RCON_HOST)"
        prompt RCON_PORT     "RCON port (RCON_PORT)"
        prompt RCON_PASSWORD "RCON password (RCON_PASSWORD)"
        echo -e "${BOLD}-- Local connection ------------------------------------${RESET}"
        prompt MC_LOCAL_HOST "Local MC IP (MC_LOCAL_HOST)"
        prompt MC_LOCAL_PORT "Local MC port (MC_LOCAL_PORT)"
        echo -e "${BOLD}-- External connection ---------------------------------${RESET}"
        prompt MC_EXT_HOST   "External MC host (MC_EXT_HOST)"
        prompt MC_EXT_PORT   "External MC port (MC_EXT_PORT)"
        echo ""
        ;;
    2)
        check_docker
        write_env
        echo -e "${GREEN}[OK] .env saved${RESET}"
        echo -e "${CYAN}[>>] Building image and starting container...${RESET}"
        cd "$SCRIPT_DIR"
        docker compose up -d --build
        echo ""
        LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || LOCAL_IP="localhost"
        echo -e "${GREEN}[OK] MCMarPanel deployed.${RESET}"
        echo -e "     Access it at: ${CYAN}http://${LOCAL_IP}:${PORT:-3007}${RESET}"
        echo ""
        break
        ;;
    3)
        write_env
        echo -e "${GREEN}[OK] .env saved (without deploying).${RESET}"
        echo ""
        ;;
    4)
        cd "$SCRIPT_DIR"
        echo -e "${CYAN}-- Logs (Ctrl+C to exit) ---------------------------${RESET}"
        docker compose logs -f
        ;;
    5)
        cd "$SCRIPT_DIR"
        echo -e "${YELLOW}[>>] Stopping container...${RESET}"
        docker compose down
        echo -e "${GREEN}[OK] Container stopped.${RESET}"
        echo ""
        ;;
    6)
        echo "Exiting."
        exit 0
        ;;
    *)
        echo -e "${RED}Invalid option.${RESET}"
        echo ""
        ;;
    esac
done
